modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "deathrecall"
version = "1.0"
displayName = "DeathRecall"
authors = "TendoArisu"
description = "输入 /back 指令回到上一次死亡地点"

[[dependencies.deathrecall]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.deathrecall]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
